cnblog/urls.py
from django.contrib import admin
from django.urls import path,re_path

from blog import views
from cnblog import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',views.login),
    path('index/',views.index),
    path('get_validCode_img/',views.get_validCode_img),
    path('register/',views.register),

    #media配置
    re_path(r'media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT})

]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User,AbstractUser

class UserInfo(AbstractUser):
    """
    用户信息表
    """
    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11,null = True,unique=True)
    avatar = models.FileField(upload_to='avatars/',default="/avatars/default.png")
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    blog = models.OneToOneField(to = 'Blog',to_field='nid',null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.username

class Blog(models.Model):
    """
    博客信息表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题',max_length=64)
    site_name = models.CharField(verbose_name='站点名称',max_length=64)
    #主题样式
    theme = models.CharField(verbose_name='博客主题',max_length = 64)
    def __str__(self):
        return self.title

class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题',max_length=64)
    blog = models.ForeignKey(verbose_name='博客主题',to='Blog',to_field='nid',on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Tag(models.Model):
    """
    文章标签
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称',max_length=64)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Article(models.Model):
    """
    文章
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题',max_length=64)
    description = models.CharField(verbose_name='文章描述',max_length=64)
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    content = models.TextField()
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    user = models.ForeignKey(verbose_name='作者',to='UserInfo',to_field='nid',on_delete=models.CASCADE)
    category = models.ForeignKey(to='Category',to_field='nid',null=True,on_delete=models.CASCADE)
    #中间模型由自己创建
    tags = models.ManyToManyField(
        to='Tag',
        through='Article2Tag',
        through_fields=('article','tag'),
    )
    def __str__(self):
        return self.title

class Article2Tag(models.Model):
    """
    文章与tag关联表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid', on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]
    def __str__(self):
        v = self.article.title + "---" + self.tag.title
        return v

class ArticleUpDown(models.Model):
    """
    点赞表
    """

    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True, on_delete=models.CASCADE)#对哪个用户点赞
    article = models.ForeignKey("Article", null=True, on_delete=models.CASCADE)#对哪篇文章点赞
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]

class Comment(models.Model):
    """

    评论表

    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

blog/views.py
from django.shortcuts import render,HttpResponse
from blog.utils import validCode


from django.http import JsonResponse
from django.contrib import auth
from blog.format_form import UserForm
from django.forms import forms
from blog.models import UserInfo


# Create your views here.
#登陆页面
def login(request):

    if request.method=="POST":
        response = {"user":None,"msg":None}
        user = request.POST.get("user")
        pwd = request.POST.get("pwd")
        valid_code = request.POST.get("valid_code")
        valid_code_str = request.session.get("valid_code_str")
        print(valid_code_str,"-----")
        if valid_code.upper() == valid_code_str.upper():
            user = auth.authenticate(username=user,password=pwd)
            if user:
                auth.login(request,user) #request.user = 当前登陆对象
                response["user"] = user.username
            else:
                response["msg"] = "username or password error!"
        else:
            response["msg"]="valid code error"
        return JsonResponse(response)


    return render(request, "blog/login.html")

#获取登陆验证图片
def get_validCode_img(request):
    img = validCode.get_valid_code_img(request)
    return  HttpResponse(img)

#主页
def index(request):
    return render(request, "blog/index.html")


#注册页面x
def register(request):
    if request.is_ajax():
        print(request.POST)
        form = UserForm(request.POST)
        #user当作一个标志位
        response = {"user":None,"msg":None}
        if form.is_valid():
            response["user"] = form.cleaned_data.get("user")
            #生成一条用户纪录
            user = form.cleaned_data.get("user")
            pwd = form.cleaned_data.get("pwd")
            email = form.cleaned_data.get("email")
            avatar_obj = request.FILES.get("avatar")
            #添加纪录
            if avatar_obj:
                UserInfo.objects.create_user(username=user,password=pwd,email = email,avatar = avatar_obj)
            else:
                UserInfo.objects.create_user(username=user,password=pwd,email = email)
        else:
            print(form.cleaned_data)
            print(form.errors)
            response["msg"] = form.errors


        return  JsonResponse(response)

    form = UserForm()

    return render(request,"blog/register.html",{"form":form})

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>{{ request.user.username }}</h3>
</body>
</html>

templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge，chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>登陆</title>

    <link rel="stylesheet" type="text/css" href="/static/blog/bootstrap/css/bootstrap.css">

    <link rel="stylesheet" type="text/css" href="/static/blog/mystyle/css/my.css">

    <!--[if lt IE 9]>
　　<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
　　<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->


</head>
<body>
<div class="container">

    <div class="row">
        <div class="col-md-5 col-md-offset-5" style="padding-top:20%;opacity:0.7">
            <form>
                {% csrf_token %}
                <div class="form-group">
                    <label for="user">用户名</label>
                    <input type="text" id="user" class="form-control" placeholder="用户名">
                </div>

                <div class="form-group">
                    <label for="pwd">密码</label>
                    <input type="password" id="pwd" class="form-control" placeholder="密码">
                </div>

                <div class="form-group">
                    <lable for="valid_code">验证码</lable>

                    <div class="row">
                        <div class="col-md-2 ck_img">
                            <input type="text" class=" valid_code form-control " id="valid_code">
                        </div>

                        <div class="col-md-2">
                            <img src="/get_validCode_img/" alt="x" class="ck_img" id="valid_code_img">
                        </div>

                    </div>
                </div>


                <input type="button" class="btn login_btn  bg-primary " value="提交">
                <span class="error"></span>
                <a href="/register/" class="btn btn-success pull-right">注册</a>

            </form>

        </div>

    </div>
</div>

<script src="/static/blog/bootstrap/js/jquery/jquery-3.1.1.min.js"></script>
<script>
    //刷新验证码
    $("#valid_code_img").click(function () {
        $(this)[0].src+="?"

    })
    //登陆验证
    $(".login_btn").click(function () {
        $.ajax({
            url:"",
            type:"post",
            data:{
                user:$("#user").val(),
                pwd:$("#pwd").val(),
                valid_code:$("#valid_code").val(),
                csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
            },
            success:function (data) {
                console.log(data);
                if (data.user){
                    location.href = "/index/"
                }else{
                    $(".error").text(data.msg).css({"color":"red","margin-left":"10px"})
                    setTimeout(function () {
                        $(".error").text("")

                    },1000)
                }
            }
        })
    })
</script>

</body>
</html>

templates/blog/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge，chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>登陆</title>

    <link rel="stylesheet" type="text/css" href="/static/blog/bootstrap/css/bootstrap.css">

    <link rel="stylesheet" type="text/css" href="/static/blog/mystyle/css/my.css">

    <!--[if lt IE 9]>
　　<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
　　<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style>
        .avatar_img{
            margin-left: 20px;
        }

        #avatar{
            display:none;
        }
        .error{
            color:red;
        }
    </style>

</head>
<body>
<div class="container">

    <div class="row">
        <div class="col-md-5 col-md-offset-5" style="padding-top:20%;opacity:0.7">
            <form id="form">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                    <label for="{{ field.auto_id}}">{{ field.label }}</label>
                    {{ field}}
                    <span class="error pull-right"></span>
                </div>
                {% endfor %}


                <div class="form-group">
                    <label for="avatar" class="avatar_img">头像
                        <img id="avatar_img_" src="/static/blog/mystyle/img/yanz.jpg" alt="x" width="50" height="60">
                    </label>
                    <input type="file" class="avatar_input" id="avatar">
                </div>

                <input type="button" class="btn  bg-primary reg_btn" value="提交"  >
                <span class="error"></span>


            </form>

        </div>

    </div>
</div>

<script src="/static/blog/bootstrap/js/jquery/jquery-3.1.1.min.js"></script>
<script>
    //头像预览

    $("#avatar").change(function () {
        //获取用户选中的文件对象
        var file_obj = $(this)[0].files[0];
        //获取文件路径
        var reader = new FileReader();
        reader.readAsDataURL(file_obj);
        //等待加载完毕
        reader.onload=function(){
            //修改img的src的属性，src=文件对象的路径
            $("#avatar_img_").attr("src",reader.result)
        }

    })
    //ajax提交注册数据
    $(".reg_btn").click(function () {
        //console.log($("#form").serializeArray());

        var formdata = new FormData();
        var request_data= $("#form").serializeArray();
        $.each(request_data,function (index,data) {
            formdata.append(data.name,data.value)
        });

        formdata.append("avatar",$("#avatar")[0].files[0]);

        {#var formdata = new FormData();#}
        {#formdata.append("user",$("#id_user").val());#}
        {#formdata.append("pwd",$("#id_pwd").val());#}
        {#formdata.append("re_pwd",$("#re_pwd").val());#}
        {#formdata.append("email",$("#id_email").val());#}
        {##}
        {#formdata.append("avatar",$("#avatar")[0].files[0]);#}
        {#formdata.append("csrfmiddlewaretoken",$("[name='csrfmiddlewaretoken']").val());#}

        $.ajax({
            url:"",
            type:"post",
            contentType:false,
            processData:false,
            data:formdata,
            success:function (data) {
                console.log(data)
                if(data.user){
                    //注册成功
                    location.href = "/login/"

                }else{
                    //清空错误信息
                    $("span.error").html("");
                    $(".form-group").removeClass("has-error");
                    $.each(data.msg,function (field,error_list) {
                        console.log(field,error_list);
                        if (field=="__all__"){

                            $("#id_re_pwd").next().html(error_list[0]).parent().addClass("has-error");
                        }


                        $("#id_"+field).next().html(error_list[0]);
                        $("#id_"+field).parent().addClass("has-error");
                    })
                }
            }
        })
    })
</script>

</body>
</html>